// ── E2E: LOINC / SNOMED term search in Item Properties modal ─────────────────
// Tests for TermSearch widget mounted inside the Codes section of CodesModal.
// Network requests to clinicaltables.nlm.nih.gov are intercepted / mocked so
// tests are deterministic and work without internet access.
//
// Run: npx playwright test tests/e2e/term-search.spec.js
//
// ── data-testid registry ──────────────────────────────────────────────────────
//   add-root-group-btn          "+Add Root Group"
//   group-add-btn               "+" button on a group
//   add-menu-item               "Item" option in add-child menu
//   action-codes                "Props" action link on an item node
//   codesModal                  Item Properties modal backdrop
//   codesModalApply             Apply button
//   codesModalCancel            Cancel button
//   codes-search-btn            "Search LOINC / SNOMED…" toggle button (prefix=code)
//   term-search-tou-accept      "Accept & enable search" button in ToU banner
//   term-search-system          custom select trigger for system choice
//   term-search-input           search text input
//   term-search-results         results container
//   term-search-result          individual result row button
//   codes-add-btn               → data-testid="codes-add-btn" generated by prefix 'code'
//   code-system-0               system input for first code row
//   code-code-0                 code input for first code row
//   code-display-0              display input for first code row
// ─────────────────────────────────────────────────────────────────────────────

import { test, expect } from '@playwright/test';

// ── Mock API response shape ───────────────────────────────────────────────────
// NLM Clinical Tables API returns: [total, codes[], extraHash, displays[]]
// displays[] each element is an array of display field values (df=text,LOINC_NUM)
const MOCK_LOINC_RESPONSE = [
  2,
  ['8480-6', '55284-4'],
  {},
  [['Systolic blood pressure'], ['Blood pressure panel with all children optional']],
];

const MOCK_SNOMED_RESPONSE = [
  1,
  ['73211009'],
  {},
  [['Diabetes mellitus']],
];

// ── Helpers ───────────────────────────────────────────────────────────────────

async function waitForLoad(page) {
  await page.waitForSelector('[data-testid="add-root-group-btn"]', { timeout: 10_000 });
}

async function freshStart(page) {
  // Clear localStorage so ToU is not pre-accepted between tests
  await page.addInitScript(() => localStorage.clear());
  await page.goto('/');
  await waitForLoad(page);
}

async function freshStartWithTouAccepted(page) {
  await page.addInitScript(() => {
    localStorage.clear();
    localStorage.setItem('loinc-tou-accepted', '1');
  });
  await page.goto('/');
  await waitForLoad(page);
}

async function addItemAndOpenCodesModal(page) {
  await page.getByTestId('add-root-group-btn').click();
  await expect(page.locator('[data-node-id="1"]')).toBeVisible();
  const group = page.locator('[data-node-id="1"]');
  await group.getByTestId('group-add-btn').click();
  await page.locator('[data-testid="add-menu-item"]').filter({ visible: true }).first().click();
  await expect(page.locator('[data-node-id="1.1"]').getByTestId('action-codes')).toBeVisible();
  await page.locator('[data-node-id="1.1"]').getByTestId('action-codes').click();
  await expect(page.locator('[data-testid="codesModal"]')).toBeVisible();
}

/** Route all NLM Clinical Tables requests to mock data. */
async function mockNlm(page) {
  await page.route('**/clinicaltables.nlm.nih.gov/**', async route => {
    const url = route.request().url();
    if (url.includes('snomed')) {
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(MOCK_SNOMED_RESPONSE) });
    } else {
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(MOCK_LOINC_RESPONSE) });
    }
  });
}

const codesModal       = (page) => page.locator('[data-testid="codesModal"]');
const searchToggleBtn  = (page) => page.getByTestId('codes-search-btn');
const touAcceptBtn     = (page) => page.getByTestId('term-search-tou-accept');
const systemSelect     = (page) => page.getByTestId('term-search-system');
const searchInput      = (page) => page.getByTestId('term-search-input');
const resultsBox       = (page) => page.getByTestId('term-search-results');
const resultRows       = (page) => page.getByTestId('term-search-result');

// ── Tests: Terms of Use ───────────────────────────────────────────────────────

test.describe('Terms of Use flow', () => {
  test('search toggle is visible in Codes section', async ({ page }) => {
    await freshStart(page);
    await addItemAndOpenCodesModal(page);
    await expect(searchToggleBtn(page)).toBeVisible();
  });

  test('clicking toggle shows ToU banner before first acceptance', async ({ page }) => {
    await freshStart(page);
    await addItemAndOpenCodesModal(page);
    await searchToggleBtn(page).click();
    await expect(touAcceptBtn(page)).toBeVisible();
    await expect(page.locator('text=LOINC Terms of Use')).toBeVisible();
  });

  test('ToU banner is absent after acceptance', async ({ page }) => {
    await freshStart(page);
    await addItemAndOpenCodesModal(page);
    await searchToggleBtn(page).click();
    await expect(touAcceptBtn(page)).toBeVisible();
    await touAcceptBtn(page).click();
    // Search UI should now appear instead of ToU
    await expect(touAcceptBtn(page)).not.toBeVisible();
    await expect(searchInput(page)).toBeVisible();
  });

  test('ToU is not shown again after acceptance (localStorage)', async ({ page }) => {
    await freshStartWithTouAccepted(page);
    await addItemAndOpenCodesModal(page);
    await searchToggleBtn(page).click();
    // Search input visible immediately, no ToU
    await expect(searchInput(page)).toBeVisible();
    await expect(touAcceptBtn(page)).not.toBeVisible();
  });
});

// ── Tests: Search UI ──────────────────────────────────────────────────────────

test.describe('Search UI', () => {
  test.beforeEach(async ({ page }) => {
    await mockNlm(page);
    await freshStartWithTouAccepted(page);
    await addItemAndOpenCodesModal(page);
    await searchToggleBtn(page).click();
    await expect(searchInput(page)).toBeVisible();
  });

  test('system selector defaults to LOINC', async ({ page }) => {
    await expect(systemSelect(page)).toHaveAttribute('data-value', 'loinc');
  });

  test('results appear after typing 2+ chars', async ({ page }) => {
    await searchInput(page).fill('blood');
    await expect(resultRows(page).first()).toBeVisible({ timeout: 5_000 });
    await expect(resultRows(page)).toHaveCount(2);
  });

  test('result row shows code and display text', async ({ page }) => {
    await searchInput(page).fill('blood');
    await expect(resultRows(page).first()).toBeVisible({ timeout: 5_000 });
    await expect(resultRows(page).first()).toContainText('8480-6');
    await expect(resultRows(page).first()).toContainText('Systolic blood pressure');
  });

  test('no results message shown when API returns empty', async ({ page }) => {
    // Override mock to return empty result set
    await page.route('**/clinicaltables.nlm.nih.gov/**', async route => {
      await route.fulfill({ status: 200, contentType: 'application/json',
        body: JSON.stringify([0, [], {}, []]) });
    });
    await searchInput(page).fill('zzzzzz');
    await expect(page.locator('text=No results found.')).toBeVisible({ timeout: 5_000 });
  });

  test('Escape clears results and input', async ({ page }) => {
    await searchInput(page).fill('blood');
    await expect(resultRows(page).first()).toBeVisible({ timeout: 5_000 });
    await searchInput(page).press('Escape');
    await expect(resultRows(page)).toHaveCount(0);
    await expect(searchInput(page)).toHaveValue('');
  });

  test('switching system to SNOMED fetches SNOMED results', async ({ page }) => {
    await systemSelect(page).click();
    await page.locator('[data-testid="csel-drop"] [data-val="snomed"]').click();
    await expect(systemSelect(page)).toHaveAttribute('data-value', 'snomed');
    await searchInput(page).fill('diab');
    await expect(resultRows(page).first()).toBeVisible({ timeout: 5_000 });
    await expect(resultRows(page).first()).toContainText('73211009');
    await expect(resultRows(page).first()).toContainText('Diabetes mellitus');
  });
});

// ── Tests: Selecting a result populates the codes row ─────────────────────────

test.describe('Selecting a result', () => {
  test.beforeEach(async ({ page }) => {
    await mockNlm(page);
    await freshStartWithTouAccepted(page);
    await addItemAndOpenCodesModal(page);
    await searchToggleBtn(page).click();
    await expect(searchInput(page)).toBeVisible();
    await searchInput(page).fill('blood');
    await expect(resultRows(page).first()).toBeVisible({ timeout: 5_000 });
  });

  test('clicking result adds a code row with correct system/code/display', async ({ page }) => {
    await resultRows(page).first().click();
    // Search panel stays open but results cleared, input cleared
    await expect(resultsBox(page).getByTestId('term-search-result')).toHaveCount(0);
    await expect(searchInput(page)).toHaveValue('');

    // New code row should appear with LOINC values
    await expect(page.getByTestId('code-system-0')).toHaveValue('http://loinc.org');
    await expect(page.getByTestId('code-code-0')).toHaveValue('8480-6');
    await expect(page.getByTestId('code-display-0')).toHaveValue('Systolic blood pressure');
  });

  test('multiple picks add multiple rows', async ({ page }) => {
    await resultRows(page).first().click();
    // Search again for the second result
    await searchInput(page).fill('blood');
    await expect(resultRows(page)).toHaveCount(2, { timeout: 5_000 });
    await resultRows(page).nth(1).click();
    // Two code rows
    await expect(page.getByTestId('code-code-0')).toHaveValue('8480-6');
    await expect(page.getByTestId('code-code-1')).toHaveValue('55284-4');
  });

  test('closing and reopening search toggle destroys widget cleanly', async ({ page }) => {
    await searchToggleBtn(page).click(); // close
    await expect(searchInput(page)).not.toBeVisible();
    await searchToggleBtn(page).click(); // re-open
    await expect(searchInput(page)).toBeVisible();
    // Input is empty after re-open
    await expect(searchInput(page)).toHaveValue('');
  });
});

// ── Tests: Apply writes codes to FHIR output ─────────────────────────────────

test.describe('End-to-end: codes saved to node', () => {
  test('code picked via search survives modal apply', async ({ page }) => {
    await mockNlm(page);
    await freshStartWithTouAccepted(page);
    await addItemAndOpenCodesModal(page);
    await searchToggleBtn(page).click();
    await searchInput(page).fill('blood');
    await expect(resultRows(page).first()).toBeVisible({ timeout: 5_000 });
    await resultRows(page).first().click();

    // Apply the modal
    await page.getByTestId('codesModalApply').click();
    await expect(codesModal(page)).not.toBeVisible();

    // Re-open and verify code persisted
    await page.locator('[data-node-id="1.1"]').getByTestId('action-codes').click();
    await expect(codesModal(page)).toBeVisible();
    await expect(page.getByTestId('code-code-0')).toHaveValue('8480-6');
    await expect(page.getByTestId('code-system-0')).toHaveValue('http://loinc.org');
    await expect(page.getByTestId('code-display-0')).toHaveValue('Systolic blood pressure');
  });
});
